baseURL = "https://www.bwoodford.xyz/"
title = "Brandon Woodford's Website"
frontmatter = "toml"
languageCode = "en-US"
pagination.pagerSize = 5

[params]
    description = "A website for Brandon Woodford's projects, thoughts, and opinions."
    mainSections = ['blog']

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false 
        lineNumbersInTable = true
        noClasses = true 
        style = "friendly"
        tabWidth = 4
