baseURL = "https://www.bwoodford.xyz/"
title = "Brandon Woodford's Website"
languageCode = "en-US"
paginate = 5

[params]
    description = "A dedicated space for my projects and musings."

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false 
        lineNumbersInTable = true
        noClasses = true 
        style = "friendly"
        tabWidth = 4
