baseURL = "http://www.norto.dev"
title = "Brandon's Blogo"
languageCode = "en-US"
paginate = 5


[params]
    description = "A website dedicated to the random crap I do."
    customCss = ["css/homepage.css"]

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersIntTable = true
        noClasses = true
        style = "tango"
        tabWidth = 4

[module]
    [[module.imports]]
        path = "github.com/IveGotNorto/hugo-hack3r-theme"
