baseURL = "https://www.norto.dev"
title = "Brandon's Blogo"
languageCode = "en-US"

[params]
    description = "Brandon Woodford's Blogo"
    customCss = ["css/homepage.css"]

[markup]
    [markup.highlight]
        anchorLineNos = true
        codeFences = true
        guessSyntax = false 
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false 
        lineNumbersIntTable = true
        noClasses = true 
        style = "dracula"
        tabWidth = 4

[module]
    [[module.imports]]
        path = "github.com/IveGotNorto/hugo-hack3r-theme"
