services:
  hugo:
    image: klakegg/hugo:0.111.3-ext-alpine
    container_name: hugo-blog
    ports:
      - "1313:1313"
    command: "server --buildDrafts --ignoreCache --noHTTPCache"
    volumes:
            - ".:/src"
    restart: always

