version: '3'

services:
  hugo:
    image: klakegg/hugo:0.86.0-ext-alpine
    container_name: hugo-blog
    ports:
      - "1313:1313"
    command: "server --buildDrafts"
    volumes:
            - ".:/src"
    restart: always

