version: '3'

services:
  hugo:
    image: klakegg/hugo:0.75.1-ext-alpine
    container_name: hugo-blog
    ports:
      - "1313:1313"
    command: server
    volumes:
            - ".:/src"
    restart: always

